### ISSUE TITLE
Facilities heading on school map modal shows even if there are no facilities

### ISSUE THREAD

**Issue by imohkay** [klpdotorg/dubdubdub#386]
@batpad silly small thing I noticed.

**Comment by imohkay** [comment]
@batpad reminder ping.

**Comment by batpad** [comment]
ah, thanks @imohkay .

@gkjohn the problem here being that on the school popups on the map page, the Facilities heading shows up even when the school does not have any facilities - i.e. none of the icons show.

Question is: What is the desired behaviour here? Should it just hide that Facilities section entirely, or show something akin to "This school has no facilities"?

Let know and will fix. Thanks!

**Comment by gkjohn** [comment]
@batpad It is unlikely that the school has no facilities. It just does not have the ones we choose to show on the popup. I'd say just hide it.
