### ISSUE TITLE
Change populatecommunitydata to populatecommunitydatav1

### ISSUE THREAD

**Issue by batpad** [klpdotorg/dubdubdub#466]
In stories/management/commands/ ... just to keep consistency with fetchcommunitydatav1 and v2 ..

Tangent: I find "populate" and "fetch" to be a little bit confusing in what they do -- I understand that populate will populate the db with the base data / question group, etc. required, and then fetch will actually fetch data from the data source and populate. But this is not immediately apparent. Not a big deal at all - just mention clearly in the docs. If you think of a better name, can rename the commands as well - but just mentioning what these mean in the docs would be fine as well.

**Comment by harisibrahimkv** [comment]
Fixed in https://github.com/klpdotorg/dubdubdub/commit/d6d99194d823e0e143e196a6d136689d145fbec6 and mentioned in https://github.com/klpdotorg/dubdubdub/wiki/Import-Scripts

@batpad Do you have any name suggestions? I just stuck to what I had used for IVRS. I agree the names are not apparent, but I can't think of anything at the moment.

**Comment by batpad** [comment]
It's ok. This is documented and the names are really fine. Closing this.
